# Generated by Django 6.0.7 on 2026-08-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='when')),
                ('quantity_move', models.IntegerField(verbose_name='quantity moved')),
                ('direction', models.CharField(blank=True, choices=[('IN', 'IN: Qty added'), ('OUT', 'OUT: Qty subtracted'), ('NONE', 'NONE: No global change')], max_length=4, null=True, verbose_name='direction')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase'), ('MANUFACTURE', 'Manufacture'), ('SALE', 'Sale'), ('LOSS', 'Loss'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RELOCATE', 'Relocate')], max_length=20, verbose_name='reason')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'movement',
                'verbose_name_plural': 'movements',
                'db_table': 'inventory_movement',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'inventory_stock',
            },
        ),
    ]
