# Generated by Django 6.0.7 on 2026-08-23 10:33

import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        ('catalogue', '0003_initial'),
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('permission_required', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movement_reasons', to='access.permission', verbose_name='Permission Required')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Movement Reason',
                'verbose_name_plural': 'Movement Reasons',
                'db_table': 'inventory_movementreason',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovementReasonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='inventory.movementreason')),
            ],
            options={
                'verbose_name': 'Movement Reason Translation',
                'db_table': 'inventory_movementreason_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_quantity', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Pack Quantity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='company.location', verbose_name='Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalogue.product', verbose_name='Product')),
                ('product_packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalogue.productpackaging', verbose_name='Product Packaging')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'inventory_stock',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pack_quantity_init', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Initial Pack Quantity')),
                ('pack_quantity_final', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Final Pack Quantity')),
                ('pack_quantity_delta', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Delta Pack Quantity')),
                ('ref_quantity_init', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Initial Ref Quantity')),
                ('ref_quantity_final', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Final Ref Quantity')),
                ('ref_quantity_delta', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Delta Ref Quantity')),
                ('snap_infos', models.JSONField(verbose_name='Snapshot Information')),
                ('created_by_comment', models.TextField(blank=True, null=True, verbose_name='User Comment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_movements', to='company.location', verbose_name='Destination Location')),
                ('location_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='company.location', verbose_name='Source Location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='catalogue.product', verbose_name='Product')),
                ('product_packaging_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_final', to='catalogue.productpackaging', verbose_name='Final Product Packaging')),
                ('product_packaging_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_init', to='catalogue.productpackaging', verbose_name='Initial Product Packaging')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.movementreason', verbose_name='Movement Reason')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movement',
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('source_company_name', models.CharField(max_length=255, verbose_name='Source Company Official Name')),
                ('source_location_parent_name', models.CharField(max_length=255, verbose_name='Source Location Parent Name')),
                ('source_product_name', models.CharField(max_length=255, verbose_name='Source Product Name')),
                ('source_product_description', models.TextField(verbose_name='Source Product Description')),
                ('source_infos', models.JSONField(verbose_name='Source Information Snapshot')),
                ('source_pack_quantity_send', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Source Pack Quantity Sent')),
                ('source_comment', models.TextField(blank=True, null=True, verbose_name='Source Comment')),
                ('source_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Source Created At')),
                ('product_sku', models.CharField(max_length=100, verbose_name='Product SKU')),
                ('dest_pack_quantity_received', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=12, null=True, verbose_name='Destination Pack Quantity Received')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED_BY_SENDER', 'Cancelled by sender'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('REFUSED_BY_RECIPIENT', 'Refused by recipient'), ('NEVER_RECEIVED', 'Never received'), ('OTHER', 'Other')], default='PENDING', max_length=50, verbose_name='Status')),
                ('dest_comment', models.TextField(blank=True, null=True, verbose_name='Destination Comment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company')),
            ],
            options={
                'verbose_name': 'Inventory Transit',
                'verbose_name_plural': 'Inventory Transits',
                'db_table': 'inventory_transit',
            },
        ),
        migrations.AddConstraint(
            model_name='movementreason',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_movement_reason_by_company_and_slug', violation_error_message='A reason movement already exists with this slug.'),
        ),
        migrations.AddConstraint(
            model_name='movementreasontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='inventory_movementreason_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'location', 'product_packaging'), name='unique_stock_by_company_location_and_packaging', violation_error_message='There is already a stock for this product, location and packaging.'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['company', 'product'], name='inventory_m_company_379738_idx'),
        ),
    ]
