# Generated by Django 6.0.7 on 2026-08-18 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.company', verbose_name='company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.location', verbose_name='location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalogue.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
                'db_table': 'inventory_stock',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='when')),
                ('quantity_move', models.IntegerField(verbose_name='quantity moved')),
                ('direction', models.CharField(blank=True, choices=[('IN', 'IN: Qty added'), ('OUT', 'OUT: Qty subtracted'), ('NONE', 'NONE: No global change')], max_length=4, null=True, verbose_name='direction')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase'), ('MANUFACTURE', 'Manufacture'), ('SALE', 'Sale'), ('LOSS', 'Loss'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('RELOCATE', 'Relocate')], max_length=20, verbose_name='reason')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='by user')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='company.company', verbose_name='company')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_movements', to='company.location', verbose_name='destination location')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_movements', to='company.location', verbose_name='source location')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stock', verbose_name='stock')),
            ],
            options={
                'verbose_name': 'movement',
                'verbose_name_plural': 'movements',
                'db_table': 'inventory_movement',
            },
        ),
    ]
