[pytest]
# Indique à Django le nom du module de configuration à importer depuis le pythonpath
DJANGO_SETTINGS_MODULE = settings

# Permet à pytest de considérer le dossier src/ comme la racine des modules Python
pythonpath = src

# addopts :
# --ds=settings : force pytest-django à utiliser src/settings.py
# --cov=src : calcule la couverture sur le code dans src/
# --cov-report=html:tests/htmlcov : envoie le rapport dans le dossier tests/
addopts = --ds=settings --cov=src --cov-report=term-missing --cov-report=html:tests/htmlcov

# Les patterns de fichiers à chercher dans tests/
python_files = tests.py test_*.py *_tests.py