"""Gabarit des unités de mesure proposées à la création d'une entreprise.

Les ratios sont exprimés par rapport à l'unique unité de référence du type :
quantité de référence = quantité saisie * ratio.

Les ratios sont des chaînes afin d'éviter toute perte de précision liée aux
flottants avant leur conversion en ``Decimal`` par le service d'import.
"""


UOM_TEMPLATES = {
    "WEIGHT": [
        {"system": "METRIC", "name": "Nanogram", "code": "ng", "is_reference": False, "ratio": "0.000000000001"},
        {"system": "METRIC", "name": "Microgram", "code": "ug", "is_reference": False, "ratio": "0.000000001000"},
        {"system": "METRIC", "name": "Milligram", "code": "mg", "is_reference": False, "ratio": "0.000001"},
        {"system": "METRIC", "name": "Centigram", "code": "cg", "is_reference": False, "ratio": "0.000010"},
        {"system": "METRIC", "name": "Decigram", "code": "dg", "is_reference": False, "ratio": "0.000100"},
        {"system": "METRIC", "name": "Gram", "code": "g", "is_reference": False, "ratio": "0.001000"},
        {"system": "METRIC", "name": "Decagram", "code": "dag", "is_reference": False, "ratio": "0.010000"},
        {"system": "METRIC", "name": "Hectogram", "code": "hg", "is_reference": False, "ratio": "0.100000"},
        {"system": "METRIC", "name": "Kilogram", "code": "kg", "is_reference": True, "ratio": "1.000000"},
        {"system": "METRIC", "name": "Metric tonne", "code": "t", "is_reference": False, "ratio": "1000.000000"},
        {"system": "IMPERIAL", "name": "Grain", "code": "gr", "is_reference": False, "ratio": "0.000064798910"},
        {"system": "IMPERIAL", "name": "Dram", "code": "dr", "is_reference": False, "ratio": "0.001771845195"},
        {"system": "IMPERIAL", "name": "Ounce", "code": "oz", "is_reference": False, "ratio": "0.028349523125"},
        {"system": "IMPERIAL", "name": "Pound", "code": "lb", "is_reference": False, "ratio": "0.453592370000"},
        {"system": "IMPERIAL", "name": "Stone", "code": "st", "is_reference": False, "ratio": "6.350293180000"},
        {"system": "IMPERIAL", "name": "US hundredweight", "code": "cwt US", "is_reference": False, "ratio": "45.359237000000"},
        {"system": "IMPERIAL", "name": "Imperial hundredweight", "code": "cwt imp", "is_reference": False, "ratio": "50.802345440000"},
        {"system": "IMPERIAL", "name": "Short ton", "code": "ton US", "is_reference": False, "ratio": "907.184740000000"},
        {"system": "IMPERIAL", "name": "Long ton", "code": "ton imp", "is_reference": False, "ratio": "1016.046908800000"},
    ],
    "LENGTH": [
        {"system": "METRIC", "name": "Nanometre", "code": "nm", "is_reference": False, "ratio": "0.000000001000"},
        {"system": "METRIC", "name": "Micrometre", "code": "um", "is_reference": False, "ratio": "0.000001"},
        {"system": "METRIC", "name": "Millimetre", "code": "mm", "is_reference": False, "ratio": "0.001000"},
        {"system": "METRIC", "name": "Centimetre", "code": "cm", "is_reference": False, "ratio": "0.010000"},
        {"system": "METRIC", "name": "Decimetre", "code": "dm", "is_reference": False, "ratio": "0.100000"},
        {"system": "METRIC", "name": "Metre", "code": "m", "is_reference": True, "ratio": "1.000000"},
        {"system": "METRIC", "name": "Decametre", "code": "dam", "is_reference": False, "ratio": "10.000000"},
        {"system": "METRIC", "name": "Hectometre", "code": "hm", "is_reference": False, "ratio": "100.000000"},
        {"system": "METRIC", "name": "Kilometre", "code": "km", "is_reference": False, "ratio": "1000.000000"},
        {"system": "IMPERIAL", "name": "Inch", "code": "in", "is_reference": False, "ratio": "0.025400"},
        {"system": "IMPERIAL", "name": "Foot", "code": "ft", "is_reference": False, "ratio": "0.304800"},
        {"system": "IMPERIAL", "name": "Yard", "code": "yd", "is_reference": False, "ratio": "0.914400"},
        {"system": "IMPERIAL", "name": "Chain", "code": "ch", "is_reference": False, "ratio": "20.116800"},
        {"system": "IMPERIAL", "name": "Furlong", "code": "fur", "is_reference": False, "ratio": "201.168000"},
        {"system": "IMPERIAL", "name": "Mile", "code": "mi", "is_reference": False, "ratio": "1609.344000"},
    ],
    "VOLUME": [
        {"system": "METRIC", "name": "Nanolitre", "code": "nL", "is_reference": False, "ratio": "0.000000001000"},
        {"system": "METRIC", "name": "Microlitre", "code": "uL", "is_reference": False, "ratio": "0.000001000000"},
        {"system": "METRIC", "name": "Millilitre", "code": "mL", "is_reference": False, "ratio": "0.001000"},
        {"system": "METRIC", "name": "Centilitre", "code": "cL", "is_reference": False, "ratio": "0.010000"},
        {"system": "METRIC", "name": "Decilitre", "code": "dL", "is_reference": False, "ratio": "0.100000"},
        {"system": "METRIC", "name": "Litre", "code": "L", "is_reference": True, "ratio": "1.000000"},
        {"system": "METRIC", "name": "Decalitre", "code": "daL", "is_reference": False, "ratio": "10.000000"},
        {"system": "METRIC", "name": "Hectolitre", "code": "hL", "is_reference": False, "ratio": "100.000000"},
        {"system": "METRIC", "name": "Kilolitre", "code": "kL", "is_reference": False, "ratio": "1000.000000"},
        {"system": "METRIC", "name": "Cubic centimetre", "code": "cm3", "is_reference": False, "ratio": "0.001000"},
        {"system": "METRIC", "name": "Cubic metre", "code": "m3", "is_reference": False, "ratio": "1000.000000"},
        {"system": "IMPERIAL", "name": "US teaspoon", "code": "tsp US", "is_reference": False, "ratio": "0.004928921594"},
        {"system": "IMPERIAL", "name": "US tablespoon", "code": "tbsp US", "is_reference": False, "ratio": "0.014786764781"},
        {"system": "IMPERIAL", "name": "US fluid ounce", "code": "fl oz US", "is_reference": False, "ratio": "0.029573529563"},
        {"system": "IMPERIAL", "name": "US cup", "code": "cup US", "is_reference": False, "ratio": "0.236588236500"},
        {"system": "IMPERIAL", "name": "US pint", "code": "pt US", "is_reference": False, "ratio": "0.473176473000"},
        {"system": "IMPERIAL", "name": "US quart", "code": "qt US", "is_reference": False, "ratio": "0.946352946000"},
        {"system": "IMPERIAL", "name": "US gallon", "code": "gal US", "is_reference": False, "ratio": "3.785411784000"},
        {"system": "IMPERIAL", "name": "US bushel", "code": "bu US", "is_reference": False, "ratio": "35.239070166880"},
        {"system": "IMPERIAL", "name": "Imperial teaspoon", "code": "tsp imp", "is_reference": False, "ratio": "0.005919388021"},
        {"system": "IMPERIAL", "name": "Imperial tablespoon", "code": "tbsp imp", "is_reference": False, "ratio": "0.017758164063"},
        {"system": "IMPERIAL", "name": "Imperial fluid ounce", "code": "fl oz imp", "is_reference": False, "ratio": "0.028413062500"},
        {"system": "IMPERIAL", "name": "Imperial gill", "code": "gi imp", "is_reference": False, "ratio": "0.142065312500"},
        {"system": "IMPERIAL", "name": "Imperial pint", "code": "pt imp", "is_reference": False, "ratio": "0.568261250000"},
        {"system": "IMPERIAL", "name": "Imperial quart", "code": "qt imp", "is_reference": False, "ratio": "1.136522500000"},
        {"system": "IMPERIAL", "name": "Imperial gallon", "code": "gal imp", "is_reference": False, "ratio": "4.546090000000"},
        {"system": "IMPERIAL", "name": "Imperial peck", "code": "pk imp", "is_reference": False, "ratio": "9.092180000000"},
        {"system": "IMPERIAL", "name": "Imperial bushel", "code": "bu imp", "is_reference": False, "ratio": "36.368720000000"},
    ],
    "AREA": [
        {"system": "METRIC", "name": "Square millimetre", "code": "mm2", "is_reference": False, "ratio": "0.000001"},
        {"system": "METRIC", "name": "Square centimetre", "code": "cm2", "is_reference": False, "ratio": "0.000100"},
        {"system": "METRIC", "name": "Square decimetre", "code": "dm2", "is_reference": False, "ratio": "0.010000"},
        {"system": "METRIC", "name": "Square metre", "code": "m2", "is_reference": True, "ratio": "1.000000"},
        {"system": "METRIC", "name": "Are", "code": "a", "is_reference": False, "ratio": "100.000000"},
        {"system": "METRIC", "name": "Hectare", "code": "ha", "is_reference": False, "ratio": "10000.000000"},
        {"system": "METRIC", "name": "Square kilometre", "code": "km2", "is_reference": False, "ratio": "1000000.000000000000"},
        {"system": "IMPERIAL", "name": "Square inch", "code": "sq in", "is_reference": False, "ratio": "0.000645160000"},
        {"system": "IMPERIAL", "name": "Square foot", "code": "sq ft", "is_reference": False, "ratio": "0.092903040000"},
        {"system": "IMPERIAL", "name": "Square yard", "code": "sq yd", "is_reference": False, "ratio": "0.836127360000"},
        {"system": "IMPERIAL", "name": "Rood", "code": "rood", "is_reference": False, "ratio": "1011.714105600000"},
        {"system": "IMPERIAL", "name": "Acre", "code": "ac", "is_reference": False, "ratio": "4046.856422400000"},
        {"system": "IMPERIAL", "name": "Square mile", "code": "sq mi", "is_reference": False, "ratio": "2589988.110336000000"},
    ],
    # Le temps n'appartient ni au système métrique ni au système impérial.
    "TIME": [
        {"system": "NONE", "name": "Millisecond", "code": "ms", "is_reference": False, "ratio": "0.001000"},
        {"system": "NONE", "name": "Second", "code": "s", "is_reference": True, "ratio": "1.000000"},
        {"system": "NONE", "name": "Minute", "code": "min", "is_reference": False, "ratio": "60.000000"},
        {"system": "NONE", "name": "Hour", "code": "h", "is_reference": False, "ratio": "3600.000000"},
        {"system": "NONE", "name": "Day", "code": "d", "is_reference": False, "ratio": "86400.000000"},
        {"system": "NONE", "name": "Week", "code": "wk", "is_reference": False, "ratio": "604800.000000"},
    ],
}
