# Generated by Django 6.0.7 on 2026-08-25 02:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('company', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_owner', models.BooleanField(default=False, help_text='Designates that this user is a company owner. He has all front-end permissions on his companies without explicitly assigning them.', verbose_name='Owner status')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('preferred_language', models.CharField(choices=[('default', 'Default'), ('en', 'English'), ('en-ca', 'English (Canada)'), ('en-us', 'English (US)'), ('fr', 'Français'), ('fr-ca', 'Français (Canada)'), ('fr-fr', 'Français (France)')], default='default', max_length=10, verbose_name='Preferred language')),
                ('preferred_home_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('scanner', 'Barcode scanner'), ('debug', 'Debug')], default='dashboard', max_length=20, verbose_name='Preferred home page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_photos', to='core.image', verbose_name='Photo')),
                ('preferred_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='company.company', verbose_name='Preferred company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_nodes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User hierarchy',
                'verbose_name_plural': 'Users hierarchies',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user assignment to the role is active. Set it to False to disable this permission instead of deleting it.', verbose_name='Is active')),
                ('company', models.ForeignKey(blank=True, help_text='The company to which the user is assigned. If None, this permission is apply to ALL companies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='company.company', verbose_name='Company')),
                ('location', models.ForeignKey(blank=True, help_text='The location to which the user is assigned. If None, this permission is apply globally.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_roles', to='company.location', verbose_name='Location')),
                ('role', models.ForeignKey(help_text='The role assigned to the user.', on_delete=django.db.models.deletion.RESTRICT, related_name='user_assignments', to='access.role', verbose_name='User role assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User role assignment')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'users_userrole',
            },
        ),
        migrations.CreateModel(
            name='UserRoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10, verbose_name='Action')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed at')),
                ('snap_infos', models.JSONField(verbose_name='Snapshot infos')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_logs_authored', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_logs', to='company.company', verbose_name='Company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_logs', to='company.location', verbose_name='Location')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_logs', to='access.role', verbose_name='Role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_logs_received', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='users.userrole', verbose_name='User role')),
            ],
            options={
                'verbose_name': 'User role log',
                'verbose_name_plural': 'User role logs',
                'db_table': 'users_userrolelog',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'company', 'location'), name='unique_user_role_company_location', violation_error_message='The user already has this role assigned to this company and location.'),
        ),
        migrations.AddIndex(
            model_name='userrolelog',
            index=models.Index(fields=['role'], name='userrole_log_role_idx'),
        ),
    ]
