# Generated by Django 6.0.7 on 2026-08-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_home_page',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('scanner', 'Barcode scanner')], default='dashboard', max_length=20),
        ),
    ]
