def get_permissions():
    """
    Retourne la liste des permissions du système.
    Les traductions anglaises sont en commentaire pour activation future.
    """
    return [
        # === ACCESS ===
        {
            "codename": "access.role.manage",
            "name": "Gérer les rôles",
            # 'name': 'Manage roles',
            "help_text": "Gérer les rôles et leur association avec des permissions. Cette permission est strictement encadrée pour empêcher l'escalade de privilèges.",
            # 'help_text': 'Manage roles and their association with permissions. This permission is strictly controlled to prevent privilege escalation.',
            "context": "DELEGATE",
            "sensibility": "HIGH",
            "display_order": 1,
        },
        # === USERS ===
        {
            "codename": "users.user.add",
            "name": "Créer un utilisateur",
            # 'name': 'Create user',
            "help_text": "Créer un nouvel utilisateur dans le système. L'utilisateur créé sera un subordonné de utilisateur créateur.",
            # 'help_text': 'Create a new user in the system. The created user will be a subordinate of the creator.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 10,
        },
        {
            "codename": "users.user.invite",
            "name": "Inviter un utilisateur",
            # 'name': 'Invite user',
            "help_text": "Inviter un utilisateur à créer son propre compte à partir d'un courriel contenant un lien sécurisé.",
            # 'help_text': 'Invite a user to create their own account from an email containing a secure link.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 11,
        },
        {
            "codename": "users.user.view",
            "name": "Voir les utilisateurs",
            # 'name': 'View users',
            "help_text": "Voir la liste des utilisateurs, incluant leur secteur d'activité. Un utilisateur avec cette permission ne voit que ses subordonnés.",
            # 'help_text': 'View the list of users, including their activity sector. A user with this permission only sees their subordinates.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 12,
        },
        {
            "codename": "users.user.change",
            "name": "Modifier un utilisateur",
            # 'name': 'Edit user',
            "help_text": "Modifier les informations ou préférences d'un utilisateur, excluant le drapeau propriétaire. Un utilisateur avec cette permission ne peut modifier que ses subordonnés.",
            # 'help_text': 'Edit user information or preferences, excluding the owner flag. A user with this permission can only edit their subordinates.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 13,
        },
        {
            "codename": "users.user.change_own",
            "name": "Modifier son propre profil",
            # 'name': 'Edit own profile',
            "help_text": "Modifier les informations et préférences de son propre profil. Exclut la modification du statut propriétaire et du superviseur.",
            # 'help_text': 'Edit own profile information and preferences. Excludes modifying owner status and supervisor.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 14,
        },
        {
            "codename": "users.user.delete",
            "name": "Supprimer un utilisateur",
            # 'name': 'Delete user',
            "help_text": "Supprimer un utilisateur. Le système refusera s'il existe des références à cet utilisateur ou s'il est propriétaire.",
            # 'help_text': 'Delete a user. The system will refuse if references exist or if the user is an owner.',
            "context": "SYSTEM",
            "sensibility": "MEDIUM",
            "display_order": 15,
        },
        {
            "codename": "users.user.setactivation",
            "name": "Activer/désactiver un compte",
            # 'name': 'Activate/deactivate account',
            "help_text": "Activer ou désactiver le compte d'un utilisateur. Un utilisateur avec cette permission ne peut changer le statut que de ses subordonnés.",
            # 'help_text': 'Activate or deactivate a user account. A user with this permission can only change status of their subordinates.',
            "context": "SYSTEM",
            "sensibility": "LOW",
            "display_order": 16,
        },
        {
            "codename": "users.userrole.view",
            "name": "Voir les rôles assignés",
            # 'name': 'View assigned roles',
            "help_text": "Consulter les rôles assignés à une liste d'utilisateurs. Un utilisateur avec cette permission ne peut voir les permissions que de ses subordonnés.",
            # 'help_text': 'View roles assigned to users. A user with this permission can only see permissions of their subordinates.',
            "context": "SYSTEM",
            "sensibility": "MEDIUM",
            "display_order": 17,
        },
        {
            "codename": "users.userrole.manage",
            "name": "Gérer les rôles assignés",
            # 'name': 'Manage assigned roles',
            "help_text": "Assigner, modifier ou supprimer les rôles assignés à un utilisateur. Strictement limité aux subordonnés et aux permissions détenues.",
            # 'help_text': 'Assign, edit or remove roles assigned to a user. Strictly limited to subordinates and held permissions.',
            "context": "SYSTEM",
            "sensibility": "HIGH",
            "display_order": 18,
        },
        {
            "codename": "users.userrolelog.view",
            "name": "Voir l'historique des rôles",
            # 'name': 'View role history',
            "help_text": "Voir l'historique des modifications sur les assignations de rôle. Un utilisateur avec cette permission ne voit les informations que de ses subordonnés.",
            # 'help_text': 'View history of role assignment changes. A user with this permission only sees information about their subordinates.',
            "context": "SYSTEM",
            "sensibility": "MEDIUM",
            "display_order": 19,
        },
        # === COMPANY ===
        {
            "codename": "company.company.view",
            "name": "Voir les informations de l'entreprise",
            # 'name': 'View company information',
            "help_text": "Voir les informations de configuration de l'entreprise.",
            # 'help_text': 'View company configuration information.',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 20,
        },
        {
            "codename": "company.locationtype.manage",
            "name": "Gérer les types de location",
            # 'name': 'Manage location types',
            "help_text": "Gérer les types de location (voir, ajouter, modifier et supprimer).",
            # 'help_text': 'Manage location types (view, add, edit and delete).',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 21,
        },
        {
            "codename": "company.location.view",
            "name": "Consulter les emplacements",
            # 'name': 'View locations',
            "help_text": "Consulter les emplacements de l'entreprise.",
            # 'help_text': 'View company locations.',
            "context": "COMPANY",
            "sensibility": "LOW",
            "display_order": 22,
        },
        {
            "codename": "company.location.sub.manage",
            "name": "Gérer les sous-locations",
            # 'name': 'Manage sub-locations',
            "help_text": "Gérer les sous-locations (emplacements enfants). Le système vérifie que le parent appartient à la même entreprise.",
            # 'help_text': 'Manage sub-locations (child locations). The system verifies the parent belongs to the same company.',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 23,
        },
        {
            "codename": "company.uom.view",
            "name": "Consulter les unités de mesure",
            # 'name': 'View units of measure',
            "help_text": "Consulter toutes les unités de mesure définies dans l'entreprise.",
            # 'help_text': 'View all units of measure defined in the company.',
            "context": "COMPANY",
            "sensibility": "LOW",
            "display_order": 24,
        },
        {
            "codename": "company.uom.manage",
            "name": "Gérer les unités de mesure",
            # 'name': 'Manage units of measure',
            "help_text": "Gérer toutes les unités de mesure utilisées dans l'entreprise.",
            # 'help_text': 'Manage all units of measure used in the company.',
            "context": "COMPANY",
            "sensibility": "HIGH",
            "display_order": 25,
        },
        # === CATALOGUE ===
        {
            "codename": "catalogue.product.view",
            "name": "Consulter le catalogue",
            # 'name': 'View catalogue',
            "help_text": "Consulter le catalogue des produits (inclut les modèles, variantes, catégories, images et conditionnement).",
            # 'help_text': 'View product catalogue (includes models, variants, categories, images and packaging).',
            "context": "COMPANY",
            "sensibility": "LOW",
            "display_order": 30,
        },
        {
            "codename": "catalogue.product.add",
            "name": "Créer un produit",
            # 'name': 'Create product',
            "help_text": "Créer un nouveau produit (inclut les modèles, variantes, catégories, images et conditionnement).",
            # 'help_text': 'Create a new product (includes models, variants, categories, images and packaging).',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 31,
        },
        {
            "codename": "catalogue.product.change",
            "name": "Modifier un produit",
            # 'name': 'Edit product',
            "help_text": "Modifier les caractéristiques d'une fiche produit (inclut les modèles, variantes, catégories, images et conditionnement).",
            # 'help_text': 'Edit product characteristics (includes models, variants, categories, images and packaging).',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 32,
        },
        {
            "codename": "catalogue.product.imagesupload",
            "name": "Téléverser des images de produit",
            # 'name': 'Upload product images',
            "help_text": "Téléverser des images sur le serveur en lien avec le produit. Nécessite la permission de modifier un produit.",
            # 'help_text': 'Upload images to the server linked to the product. Requires product edit permission.',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 33,
        },
        {
            "codename": "catalogue.product.archive",
            "name": "Archiver un produit",
            # 'name': 'Archive product',
            "help_text": "Archiver ou désarchiver un produit. Un produit archivé n'apparaît plus dans les listes ni les recherches.",
            # 'help_text': 'Archive or unarchive a product. An archived product no longer appears in lists or searches.',
            "context": "COMPANY",
            "sensibility": "HIGH",
            "display_order": 34,
        },
        {
            "codename": "catalogue.product.delete",
            "name": "Supprimer un produit",
            # 'name': 'Delete product',
            "help_text": "Supprimer définitivement un produit du catalogue. Le système bloquera la suppression si des références existent.",
            # 'help_text': 'Permanently delete a product from the catalogue. The system will block deletion if references exist.',
            "context": "COMPANY",
            "sensibility": "HIGH",
            "display_order": 35,
        },
        {
            "codename": "catalogue.category.view",
            "name": "Consulter les catégories",
            # 'name': 'View categories',
            "help_text": "Consulter l'arborescence complète des catégories.",
            # 'help_text': 'View the complete category tree.',
            "context": "COMPANY",
            "sensibility": "LOW",
            "display_order": 36,
        },
        {
            "codename": "catalogue.category.manage",
            "name": "Gérer les catégories",
            # 'name': 'Manage categories',
            "help_text": "Gérer les catégories. Le système bloquera la suppression d'une catégorie référencée.",
            # 'help_text': 'Manage categories. The system will block deletion of a referenced category.',
            "context": "COMPANY",
            "sensibility": "MEDIUM",
            "display_order": 37,
        },
        {
            "codename": "catalogue.attribute.manage",
            "name": "Gérer les attributs de variantes",
            # 'name': 'Manage variant attributes',
            "help_text": "Gérer les attributs (clé et valeurs) de variantes de produit dans un module dédié.",
            # 'help_text': 'Manage product variant attributes (keys and values) in a dedicated module.',
            "context": "COMPANY",
            "sensibility": "HIGH",
            "display_order": 38,
        },
        # === INVENTORY ===
        {
            "codename": "inventory.stock.view",
            "name": "Consulter les stocks",
            # 'name': 'View stock',
            "help_text": "Consulter les quantités de stock disponibles.",
            # 'help_text': 'View available stock quantities.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 40,
        },
        {
            "codename": "inventory.movement.view",
            "name": "Consulter les mouvements de stock",
            # 'name': 'View stock movements',
            "help_text": "Consulter le journal historique des mouvements de stock. Permet de rechercher et filtrer.",
            # 'help_text': 'View stock movement history journal. Allows searching and filtering.',
            "context": "COMPANY",
            "sensibility": "LOW",
            "display_order": 41,
        },
        {
            "codename": "inventory.movementreason.manage",
            "name": "Gérer les raisons de mouvement",
            # 'name': 'Manage movement reasons',
            "help_text": "Gérer les raisons pour modifier les quantités en inventaire. Permet d'associer la permission requise à la raison.",
            # 'help_text': 'Manage reasons for inventory quantity changes. Allows associating required permission to the reason.',
            "context": "COMPANY",
            "sensibility": "HIGH",
            "display_order": 42,
        },
        {
            "codename": "inventory.stock.increase",
            "name": "Augmenter l'inventaire",
            # 'name': 'Increase inventory',
            "help_text": "Augmenter l'inventaire (permission générique).",
            # 'help_text': 'Increase inventory (generic permission).',
            "context": "LOCATION",
            "sensibility": "HIGH",
            "display_order": 43,
        },
        {
            "codename": "inventory.stock.decrease",
            "name": "Diminuer l'inventaire",
            # 'name': 'Decrease inventory',
            "help_text": "Diminuer l'inventaire (permission générique).",
            # 'help_text': 'Decrease inventory (generic permission).',
            "context": "LOCATION",
            "sensibility": "HIGH",
            "display_order": 44,
        },
        {
            "codename": "inventory.stock.purchase",
            "name": "Réception achat fournisseur",
            # 'name': 'Supplier purchase receipt',
            "help_text": "Augmenter l'inventaire en raison d'une commande d'achat à un fournisseur.",
            # 'help_text': 'Increase inventory due to supplier purchase order.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 45,
        },
        {
            "codename": "inventory.stock.manufacture",
            "name": "Réception production interne",
            # 'name': 'Internal production receipt',
            "help_text": "Augmenter l'inventaire en raison de l'arrivée de produits issus d'une chaîne de production interne.",
            # 'help_text': 'Increase inventory due to products from internal production line.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 46,
        },
        {
            "codename": "inventory.stock.sale",
            "name": "Vente",
            # 'name': 'Sale',
            "help_text": "Diminuer l'inventaire en raison d'une vente.",
            # 'help_text': 'Decrease inventory due to a sale.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 47,
        },
        {
            "codename": "inventory.stock.count_more",
            "name": "Ajustement inventaire (plus)",
            # 'name': 'Inventory adjustment (plus)',
            "help_text": "Augmenter l'inventaire en raison d'un ajustement de décompte d'inventaire.",
            # 'help_text': 'Increase inventory due to inventory count adjustment.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 48,
        },
        {
            "codename": "inventory.stock.count_less",
            "name": "Ajustement inventaire (moins)",
            # 'name': 'Inventory adjustment (minus)',
            "help_text": "Diminuer l'inventaire en raison d'un ajustement de décompte d'inventaire.",
            # 'help_text': 'Decrease inventory due to inventory count adjustment.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 49,
        },
        {
            "codename": "inventory.stock.loss",
            "name": "Perte de marchandise",
            # 'name': 'Merchandise loss',
            "help_text": "Diminuer l'inventaire en raison de marchandises perdues (bris, vol, date de péremption dépassé, etc).",
            # 'help_text': 'Decrease inventory due to lost merchandise (breakage, theft, expiry, etc).',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 50,
        },
        {
            "codename": "inventory.stock.uom_pack",
            "name": "Changement d'UM (pack)",
            # 'name': 'UoM change (pack)',
            "help_text": "Diminuer l'inventaire en raison d'un changement d'unité de mesure (unité vers pack).",
            # 'help_text': 'Decrease inventory due to unit of measure change (unit to pack).',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 51,
        },
        {
            "codename": "inventory.stock.uom_unpack",
            "name": "Changement d'UM (unpack)",
            # 'name': 'UoM change (unpack)',
            "help_text": "Augmenter l'inventaire en raison d'un changement d'unité de mesure (pack vers unité).",
            # 'help_text': 'Increase inventory due to unit of measure change (pack to unit).',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 52,
        },
        {
            "codename": "inventory.stock.relocate",
            "name": "Relocaliser dans même emplacement",
            # 'name': 'Relocate within same location',
            "help_text": "Relocaliser le stock dans un emplacement ayant le même parent principal.",
            # 'help_text': 'Relocate stock within a location having the same main parent.',
            "context": "MULTI_LOCATIONS",
            "sensibility": "MEDIUM",
            "display_order": 53,
        },
        {
            "codename": "inventory.stock.transfer_out",
            "name": "Transfert sortant",
            # 'name': 'Outbound transfer',
            "help_text": "Diminuer l'inventaire pour l'envoyer dans un emplacement ayant un parent principal différent.",
            # 'help_text': 'Decrease inventory to send to a location with a different main parent.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 54,
        },
        {
            "codename": "inventory.stock.transfer_in",
            "name": "Transfert entrant",
            # 'name': 'Inbound transfer',
            "help_text": "Augmenter l'inventaire en réceptionnant un transfert entrant.",
            # 'help_text': 'Increase inventory by receiving an inbound transfer.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 55,
        },
        {
            "codename": "inventory.stock.intercompany_out",
            "name": "Transfert inter-compagnie sortant",
            # 'name': 'Inter-company outbound transfer',
            "help_text": "Diminuer l'inventaire en raison d'une vente interne vers une entreprise du même propriétaire.",
            # 'help_text': 'Decrease inventory due to internal sale to a company of the same owner.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 56,
        },
        {
            "codename": "inventory.stock.intercompany_in",
            "name": "Transfert inter-compagnie entrant",
            # 'name': 'Inter-company inbound transfer',
            "help_text": "Augmenter l'inventaire en raison de la réception interne de stock d'une entreprise du même propriétaire.",
            # 'help_text': 'Increase inventory due to internal receipt from a company of the same owner.',
            "context": "LOCATION",
            "sensibility": "MEDIUM",
            "display_order": 57,
        },
        # === REPORTING ===
        {
            "codename": "reporting.view",
            "name": "Voir les rapports consolidés",
            # 'name': 'View consolidated reports',
            "help_text": "Lecture des rapports rassemblant les données de plusieurs entreprises.",
            # 'help_text': 'Read reports gathering data from multiple companies.',
            "context": "MULTI_COMPANIES",
            "sensibility": "HIGH",
            "display_order": 60,
        },
        {
            "codename": "reporting.stock_levels.view",
            "name": "Voir les rapports de stock",
            # 'name': 'View stock level reports',
            "help_text": "Lecture des rapports de rotations, ruptures imminentes et seuils d'alerte.",
            # 'help_text': 'Read reports on turnover, imminent shortages and alert thresholds.',
            "context": "MULTI_COMPANIES",
            "sensibility": "HIGH",
            "display_order": 61,
        },
    ]
