# Generated by Django 6.0.7 on 2026-08-23 10:33

import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('postal_code', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Postal code')),
                ('time_zone', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Time zone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'company_address',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddressTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('street_address', models.CharField(blank=True, default=None, help_text='Street name, number, P.O. box', max_length=255, null=True, verbose_name='Street address')),
                ('extended_address', models.CharField(blank=True, default=None, help_text='Apartment, suite, unit, building, floor', max_length=255, null=True, verbose_name='Extended address')),
                ('locality', models.CharField(blank=True, default=None, help_text='City, town, or village', max_length=150, null=True, verbose_name='Locality')),
                ('region', models.CharField(blank=True, default=None, help_text='State, province, county, or canton', max_length=150, null=True, verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Address Translation',
                'db_table': 'company_address_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('official_name', models.CharField(max_length=150, unique=True, verbose_name='Official name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('accept_negative_stock', models.BooleanField(default=False, verbose_name='Accept negative stock')),
                ('translation_mode', models.CharField(choices=[('DISABLED', 'Disable data translation'), ('LANGUAGE', 'Generic translations (en, fr, etc)'), ('REGIONAL', 'Full translations (with regional variants)')], default='DISABLED', help_text='Defines how dynamic company data translations are handled: disabled (only 1 language), generic languages, or with regional variants.', max_length=20, verbose_name='Translation mode')),
                ('is_active', models.BooleanField(default=True, help_text='An inactive company becomes read-only: its settings, catalogue, and inventory can no longer be modified and it is excluded from consolidated reports.', verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company_company',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Company Translation',
                'db_table': 'company_company_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=2, unique=True, verbose_name='ISO code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'company_country',
                'ordering': ['iso_code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country Translation',
                'db_table': 'company_country_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'company_location',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Location Translation',
                'db_table': 'company_location_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('is_stockable', models.BooleanField(default=True, help_text='If disabled, locations of this type cannot be selected for inventory storage.', verbose_name='Stockable')),
            ],
            options={
                'verbose_name': 'Location type',
                'verbose_name_plural': 'Location types',
                'db_table': 'company_locationtype',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LocationTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Location type Translation',
                'db_table': 'company_locationtype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Uom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('type', models.CharField(choices=[('UNIT', 'Unit'), ('WEIGHT', 'Weight'), ('LENGTH', 'Length'), ('VOLUME', 'Volume'), ('AREA', 'Area'), ('TIME', 'Time')], max_length=20, verbose_name='Type')),
                ('system', models.CharField(choices=[('NONE', 'None'), ('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='NONE', max_length=20, verbose_name='System')),
                ('is_reference', models.BooleanField(default=False, verbose_name='Is reference')),
                ('ratio', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Ratio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Unit of measure',
                'verbose_name_plural': 'Units of measure',
                'db_table': 'company_uom',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UomTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Unit of measure Translation',
                'db_table': 'company_uom_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
