# Generated by Django 6.0.7 on 2026-08-18 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(max_length=255, unique=True, verbose_name='official name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'company_company',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address (line 1)')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address (line 2)')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('state_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='state or province')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='company.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'company_location',
            },
        ),
    ]
