# Generated by Django 6.0.7 on 2026-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='official_name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='official_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
