# Generated by Django 6.0.7 on 2026-08-23 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uom',
            name='unique_reference_uom_per_company_type',
        ),
        migrations.AddField(
            model_name='uom',
            name='is_ref_unique_check',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(is_reference=True, then=models.Value(1)), default=None, output_field=models.IntegerField()), null=True, output_field=models.IntegerField()),
        ),
        migrations.AddConstraint(
            model_name='uom',
            constraint=models.UniqueConstraint(fields=('company', 'type', 'is_ref_unique_check'), name='unique_reference_uom_per_company_type', violation_error_message='A reference unit already exists for this type.'),
        ),
    ]
