# Generated by Django 6.0.7 on 2026-08-29 00:21

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_initial'),
        ('company', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_images', to='core.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalogue.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.attributevalue', verbose_name='Attribute value'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='catalogue.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='company.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_configs', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productfamily',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='catalogue.productfamily', verbose_name='Product family'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogue.productfamily', verbose_name='Product family'),
        ),
        migrations.AddField(
            model_name='productfamilyimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productfamilyimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_family_images', to='core.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productfamilyimage',
            name='product_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_family_images', to='catalogue.productfamily', verbose_name='Product family'),
        ),
        migrations.AddField(
            model_name='productfamilytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalogue.productfamily'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_packagings', to='company.uom', verbose_name='Base unit of measure'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='catalogue.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='productconfig',
            name='product_packaging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='catalogue.productpackaging', verbose_name='Product packaging'),
        ),
        migrations.AddField(
            model_name='productpackagingtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalogue.productpackaging'),
        ),
        migrations.AddConstraint(
            model_name='attributekey',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_slug_attributekey_by_company', violation_error_message='This slug is already used in this company.'),
        ),
        migrations.AddConstraint(
            model_name='attributekeytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='catalogue_attributekey_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='attributevaluetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='catalogue_attributevalue_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_slug_category_by_company', violation_error_message='This slug is already used in this company.'),
        ),
        migrations.AddConstraint(
            model_name='categorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='catalogue_category_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productattributes',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_value'), name='unique_product_attributevalue', violation_error_message='This attribute value is already linked to this product.'),
        ),
        migrations.AddConstraint(
            model_name='productfamily',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_slug_productmodel_by_company', violation_error_message='This slug is already used in this company.'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product_family', 'category'), name='unique_productmodel_category', violation_error_message='This category is already linked to this product family.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_slug_product_by_company', violation_error_message='This slug is already used in this company.'),
        ),
        migrations.AddConstraint(
            model_name='productfamilyimage',
            constraint=models.UniqueConstraint(fields=('product_family', 'image'), name='unique_productmodel_image', violation_error_message='This image is already linked to this product family.'),
        ),
        migrations.AddConstraint(
            model_name='productfamilytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='catalogue_productfamily_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'image'), name='unique_product_image', violation_error_message='This image is already linked to this product.'),
        ),
        migrations.AddConstraint(
            model_name='productpackagingtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='catalogue_productpackaging_translation_uniq_lang'),
        ),
    ]
