# Generated by Django 6.0.7 on 2026-08-18 23:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('context', models.CharField(choices=[('SYSTEM', 'System'), ('DELEGATE', 'Delegate'), ('COMPANY', 'Company'), ('MULTI_COMPANIES', 'Multi-companies'), ('LOCATION', 'Location'), ('MULTI_LOCATIONS', 'Multi-locations')], max_length=20, verbose_name='Context')),
                ('sensibility', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10, verbose_name='Sensibility')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Access permission',
                'verbose_name_plural': 'Access permissions',
                'db_table': 'access_permission',
                'ordering': ['display_order', 'codename'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Access Role permission',
                'verbose_name_plural': 'Access Role permissions',
                'db_table': 'access_rolepermissions',
            },
        ),
        migrations.CreateModel(
            name='RoleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Access role Translation',
                'db_table': 'access_role_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PermissionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='Help text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='access.permission')),
            ],
            options={
                'verbose_name': 'Access permission Translation',
                'db_table': 'access_permission_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Access role',
                'verbose_name_plural': 'Access roles',
                'db_table': 'access_role',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
