# Generated by Django 6.0.7 on 2026-08-18 23:40

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='access.RolePermission', to='access.permission', verbose_name='Permissions'),
        ),
        migrations.AddField(
            model_name='roletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='access.role'),
        ),
        migrations.AddConstraint(
            model_name='permissiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='access_permission_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission', violation_error_message='This role already has this permission assigned.'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('slug', 'company'), name='unique_role_per_company', violation_error_message='A role with this slug already exists for this company.'),
        ),
        migrations.AddConstraint(
            model_name='roletranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='access_role_translation_uniq_lang'),
        ),
    ]
