# Generated by Django 6.0.7 on 2026-08-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_custom_access_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDelegate',
            fields=[
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('access.role',),
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Access log', 'verbose_name_plural': 'Access logs'},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='created_at',
            new_name='changed_at',
        ),
    ]
