name: Django CI & Coverage

on:
  push:
    branches: [ master, tests ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    # Configuration du service MySQL pour la base de données de test
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_django_stock
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Récupérer le code source
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécuter les tests avec Pytest & Coverage
      env:
        # Données factuelles pour que django-environ ne lève pas d'erreur
        DEBUG: "True"
        SECRET_KEY: "DJANGO-SECRET-KEY-TO-DEFINE-FOR-CI"
        DB_NAME: "test_django_stock"
        DB_USER: "root"        # Le conteneur MySQL de GitHub utilise 'root' par défaut
        DB_PASSWORD: ""        # Le conteneur MySQL de GitHub a un mot de passe vide par défaut
        DB_HOST: "127.0.0.1"
        DB_PORT: "3306"
        DEFAULT_LANG: "fr"
        TIME_ZONE: "America/Toronto"
      run: |
        pytest --cov=src --cov-report=term-missing > pytest-coverage.txt

    - name: Générer le Badge de Couverture
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        badge-title: Test coverage
        hide-report: true
        create-new-comment: false